### ISSUE TITLE
Using grid map as the transmission protocol between multiple robot to run MR_SLAM？

### ISSUE THREAD

**Issue by Joosoo1** [MaverickPeter/MR_SLAM#16]
Hello, here I am again, recently I'm working on multi-robot grid map stitching, and I'm planning to utilize MR_SLAM for this work, I'm utilizing 2.5d grid maps as a transfer medium between robots, first I remap the 2.5d grid maps to point cloud maps in the backend, and then I input the point clouds into LoopDetection and Mmapping, MR_ SLAM can work well (good news). I have an idea about this, can we use the grid map to construct the pose graph, use the point cloud after the grid map conversion for LoopDetection, after that use the loopback constraints for grid map pose graph optimization, and use the optimized pose graph for grid sub-map splicing, I think this can reduce a lot of computation, do you think this is feasible?

**Comment by MaverickPeter** [comment]
@Joosoo1 
Do you mean that we send the point cloud from 2.5d grid maps between robots rather than the keyframe point cloud? The key factor here is the performance of the loop detection module using the grid map. If the performance is fully evaluated and satisfied, then the transmission data and computation will be largely reduced, just as you said.

**Comment by Joosoo1** [comment]
Ok, I see, thanks for the reply, I will keep researching in send 2.5d grid maps between robots
