### ISSUE TITLE
Inconsistent loop optimization

### ISSUE THREAD

**Issue by Joosoo1** [MaverickPeter/MR_SLAM#21]
Hi all, I recently found some issues when running mr_slam deployments locally. There is a conflict in loopback optimization (loopback optimization), the previous loopback stitched the maps between multiple machines nicely, but after some time, a new loopback was generated but it corrupted the previously stitched maps, resulting in the inability to generate globally consistent maps. What is causing this problem and how can I fix it, please give me some suggestions. 
Here is how my localization runs:
 Initial loop: https://github.com/MaverickPeter/MR_SLAM/assets/65029285/c9950770-0703-4efe-a662-afdb2267f95b
 Initial loop is corrupted by subsequent loopback optimizations: https://github.com/MaverickPeter/MR_SLAM/assets/65029285/d11db669-851d-4958-9bfc-25763ea530ce

**Comment by MaverickPeter** [comment]
@Joosoo1 Can you try to set a lower number of the param "icp_fitness_score" in the py file in the loop detection module and see if the problem is solved? If the problem persists, I suggest you provide the terminal output during inconsistency (optimization log), I'll have more chances to locate the problem and solve it.

**Comment by Joosoo1** [comment]
Okay, I'll follow up with you via e-mail.
